### ISSUE TITLE
[audit] Onboarding audit (May 22)

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#58]
It's been a while, we should see how this experience feels. I should also document the steps so other people can easily do it.

**Comment by jonbell-lot23** [comment]
Completed this, and here are my findings:

## Bugs (fixed)

- [ ]  Our settings import was broken ([[bug](https://github.com/RecordReplay/gecko-dev/issues/859)](https://github.com/RecordReplay/gecko-dev/issues/859))

## Bugs (open)

- [ ]  Adobe Acrobat is the first thing you see ([[bug](https://github.com/RecordReplay/gecko-dev/issues/752)](https://github.com/RecordReplay/gecko-dev/issues/752))
- [ ]  Logging out takes you to [[localhost:3000](http://localhost:3000/)](http://localhost:3000) ([[bug](https://github.com/RecordReplay/devtools/issues/7006)](https://github.com/RecordReplay/devtools/issues/7006))

## Polish items

- We still have polish items in our onboarding screens (wrong colors, big ugly white boxes, copy) but these issues aren’t actively causing onboarding issues.
- We have a console.log item that’s an empty string and should instead be “—-”

## Additional thoughts

It would be really helpful to have a way to fully delete a user from the DB because otherwise we can’t see what a new user sees without a lot of effort. This is where bugs are going to hide.
